export const landingToolsContent = {
  de: {
    kicker: "ASDAR Potenzial-Check",
    heading: "Finden Sie in 2 Minuten den ersten sinnvollen Automatisierungshebel.",
    intro:
      "Ein geführter Check mit Profil, Reifegrad, Engpass, Zeitwert und einem konkreten nächsten Schritt.",
    steps: ["Profil", "Lage", "Wert & Ergebnis"],
    profileTitle: "1. Profil wählen",
    profileHint:
      "Das Profil setzt realistische Standardwerte für die Zeitrechnung. Die fünf Lagefragen beantworten Sie danach selbst.",
    selectedProfile: "Ausgewähltes Profil",
    readinessTitle: "2. Lage einschätzen",
    readinessHint:
      "Beantworten Sie alle fünf Fragen. Erst danach wird der Score sichtbar.",
    valueTitle: "3. Zeitwert und Ergebnis",
    valueHint:
      "Passen Sie die Annahmen an. Das Ergebnis bleibt live mit Ihrer Lagebewertung verbunden.",
    scale: ["Gar nicht", "Kaum", "Teilweise", "Überwiegend", "Voll"],
    unanswered: "Offen",
    answered: "beantwortet",
    industries: [
      {
        key: "practice",
        label: "Praxis & Therapie",
        hint: "Anfragen, Termine, Dokumentation und wiederkehrende Patientenkommunikation.",
        focus: "Patientenkommunikation und Dokumentation",
        people: 6,
        manualHours: 5,
        hourlyRate: 42,
        automationRate: 25,
      },
      {
        key: "dealership",
        label: "Autohaus",
        hint: "Leads, Probefahrten, Angebote, Finanzierung und Nachfass-Mails.",
        focus: "Lead-Triage und Angebotsvorbereitung",
        people: 9,
        manualHours: 4,
        hourlyRate: 48,
        automationRate: 30,
      },
      {
        key: "cleaning",
        label: "Reinigung",
        hint: "Aufträge, Reklamationen, Touren, Statusfragen und Standards.",
        focus: "Auftragsstatus und Kundenkommunikation",
        people: 12,
        manualHours: 3,
        hourlyRate: 32,
        automationRate: 25,
      },
      {
        key: "agency",
        label: "Agentur & Dienstleister",
        hint: "Briefings, Angebote, Protokolle, Reporting und Wissenssuche.",
        focus: "Briefings, Angebote und Reporting",
        people: 8,
        manualHours: 6,
        hourlyRate: 65,
        automationRate: 35,
      },
      {
        key: "other",
        label: "Anderes Unternehmen",
        hint: "Ein neutraler Startwert für wiederkehrende Backoffice- oder Serviceprozesse.",
        focus: "Wiederkehrender manueller Kernprozess",
        people: 8,
        manualHours: 4,
        hourlyRate: 45,
        automationRate: 25,
      },
    ],
    areas: [
      {
        label: "Prozessklarheit",
        description: "Die wichtigsten Abläufe sind bekannt und wiederholbar.",
        lever: "den Ablauf mit dem höchsten manuellen Aufwand sichtbar machen",
        actions: [
          "Einen klar abgegrenzten Prozess mit Start, Ende und Beteiligten wählen.",
          "Drei typische Fälle aus den letzten Wochen sammeln.",
          "Doppelarbeit, Wartezeiten und Medienbrüche markieren.",
        ],
      },
      {
        label: "Daten & Dokumente",
        description: "Informationen sind auffindbar und nicht nur in E-Mails verteilt.",
        lever: "die Daten- und Dokumentenbasis für einen Pilot ordnen",
        actions: [
          "Die wichtigsten Vorlagen, Dateien und Datentabellen an einem Ort sammeln.",
          "Fehlende Pflichtfelder und doppelte Datenquellen sichtbar machen.",
          "Eine minimale Struktur für den Pilot definieren.",
        ],
      },
      {
        label: "Tool-Klarheit",
        description: "Die wichtigsten Systeme sind bekannt und sinnvoll nutzbar.",
        lever: "die Tool-Landschaft auf einen einfachen Workflow reduzieren",
        actions: [
          "Alle Systeme notieren, die im Prozess berührt werden.",
          "Manuelle Übertragungen zwischen Tools markieren.",
          "Entscheiden, welches System für den Pilot führend ist.",
        ],
      },
      {
        label: "Umsetzungskapazität",
        description: "Es gibt Zeit und eine verantwortliche Person für einen Pilot.",
        lever: "einen kleinen Pilot mit klarem Owner aufsetzen",
        actions: [
          "Eine verantwortliche Person für Entscheidungen benennen.",
          "Ein kleines Zeitfenster pro Woche für Tests reservieren.",
          "Den Pilot so schneiden, dass er in zwei bis vier Wochen messbar ist.",
        ],
      },
      {
        label: "Umsetzungswille",
        description: "Entscheider sind bereit, einen pragmatischen Pilot zu testen.",
        lever: "die Entscheidung für einen messbaren Quick Win absichern",
        actions: [
          "Ein Erfolgskriterium vor dem Start festlegen.",
          "Klären, welche Aufgabe entlastet werden soll und welche nicht.",
          "Das Team früh über Ziel, Grenzen und Kontrolle informieren.",
        ],
      },
    ],
    feedback: {
      low: "Hoher Hebel: Hier braucht es zuerst Klarheit, bevor Automatisierung trägt.",
      mid: "Guter Pilotbereich: Es gibt Substanz, aber noch sichtbare Reibung.",
      high: "Starke Basis: Dieser Bereich kann den Pilot beschleunigen.",
      prefix: "Ihre letzte Antwort zeigt",
    },
    bands: [
      {
        max: 44,
        label: "Erst Klarheit schaffen",
        phase: "Analysieren + Strukturieren",
        body: "Der größte Hebel liegt wahrscheinlich darin, Abläufe, Daten und Verantwortlichkeiten sauber sichtbar zu machen.",
        nextStep: "90 Minuten Prozessaufnahme und ASDAR Baseline.",
      },
      {
        max: 71,
        label: "Pilot vorbereiten",
        phase: "Strukturieren + Digitalisieren",
        body: "Es gibt genug Substanz für Quick Wins. Jetzt braucht es Priorisierung, Datenbasis und einen kleinen Testfall.",
        nextStep: "Use-Case-Auswahl, Aufwand/Nutzen-Matrix und Pilotplan.",
      },
      {
        max: 100,
        label: "Automatisierung starten",
        phase: "Automatisieren + Realisieren",
        body: "Die Grundlage wirkt belastbar. Jetzt lohnt sich ein konkreter Workflow-Pilot mit klaren Messpunkten.",
        nextStep: "Automatisierungs-Sprint mit Zielmetriken und Portal-Status.",
      },
    ],
    resultTitle: "Persönliches Ergebnis",
    lockedTitle: "Score wird nach 5 Antworten sichtbar",
    lockedBody:
      "Wählen Sie Ihr Profil und beantworten Sie die Lagefragen. Danach sehen Sie Score, Engpass, ersten Hebel und Zeitwert.",
    bottleneck: "Größter Engpass",
    firstLever: "Erster Automatisierungshebel",
    nextActions: "Nächste sinnvolle Aktionen",
    nextStep: "Beratungsschritt",
    people: "Beteiligte Personen",
    hours: "Manuelle Stunden pro Person/Woche",
    rate: "Interner Stundensatz",
    automation: "Realistisch reduzierbarer Anteil",
    monthlyHours: "Stunden pro Monat frei",
    monthlyValue: "Wert pro Monat",
    annualValue: "Wert pro Jahr",
    assumptionsTitle: "Wie der Zeitwert gerechnet wird",
    assumptionsBody:
      "Formel: Personen x manuelle Stunden pro Woche x 4,33 x reduzierbarer Anteil. Der Euro-Wert nutzt Ihren internen Stundensatz. Das ist eine Orientierung, keine Garantie.",
    cta: "Ergebnis im Erstgespräch besprechen",
    mobileCta: "Ergebnis besprechen",
    next: "Weiter",
    back: "Zurück",
    editAnswers: "Antworten anpassen",
    revealHint: "Noch {count} Antwort(en) bis zum Ergebnis.",
    disclaimer:
      "Beispielrechnung, keine Garantie. Die echte Bewertung passiert mit echten Prozessdaten im Projekt.",
  },
  en: {
    kicker: "ASDAR potential check",
    heading: "Find the first useful automation lever in 2 minutes.",
    intro:
      "A guided check with profile, readiness, bottleneck, time value, and one concrete next step.",
    steps: ["Profile", "State", "Value & result"],
    profileTitle: "1. Choose a profile",
    profileHint:
      "The profile sets realistic defaults for the time calculation. You answer the five readiness questions yourself next.",
    selectedProfile: "Selected profile",
    readinessTitle: "2. Estimate your current state",
    readinessHint:
      "Answer all five questions. The score unlocks only after that.",
    valueTitle: "3. Time value and result",
    valueHint:
      "Adjust the assumptions. The result stays connected to your readiness answers.",
    scale: ["Not yet", "Barely", "Partly", "Mostly", "Fully"],
    unanswered: "Open",
    answered: "answered",
    industries: [
      {
        key: "practice",
        label: "Practice & therapy",
        hint: "Inquiries, appointments, documentation, and recurring patient communication.",
        focus: "Patient communication and documentation",
        people: 6,
        manualHours: 5,
        hourlyRate: 42,
        automationRate: 25,
      },
      {
        key: "dealership",
        label: "Car dealership",
        hint: "Leads, test drives, quotes, financing, and follow-up emails.",
        focus: "Lead triage and quote preparation",
        people: 9,
        manualHours: 4,
        hourlyRate: 48,
        automationRate: 30,
      },
      {
        key: "cleaning",
        label: "Cleaning service",
        hint: "Orders, complaints, routes, status questions, and standards.",
        focus: "Order status and customer communication",
        people: 12,
        manualHours: 3,
        hourlyRate: 32,
        automationRate: 25,
      },
      {
        key: "agency",
        label: "Agency & services",
        hint: "Briefings, proposals, minutes, reporting, and knowledge search.",
        focus: "Briefings, proposals, and reporting",
        people: 8,
        manualHours: 6,
        hourlyRate: 65,
        automationRate: 35,
      },
      {
        key: "other",
        label: "Another business",
        hint: "A neutral starting point for recurring back-office or service workflows.",
        focus: "Recurring manual core process",
        people: 8,
        manualHours: 4,
        hourlyRate: 45,
        automationRate: 25,
      },
    ],
    areas: [
      {
        label: "Process clarity",
        description: "The key workflows are known and repeatable.",
        lever: "make the highest-effort manual workflow visible",
        actions: [
          "Choose one bounded process with a clear start, end, and participants.",
          "Collect three typical cases from the last few weeks.",
          "Mark duplicate work, waits, and handoffs between media.",
        ],
      },
      {
        label: "Data & documents",
        description: "Information is findable and not only scattered across emails.",
        lever: "organize the data and document base for one pilot",
        actions: [
          "Collect the key templates, files, and tables in one place.",
          "Make missing required fields and duplicate data sources visible.",
          "Define the smallest useful structure for the pilot.",
        ],
      },
      {
        label: "Tool clarity",
        description: "The key systems are known and usable.",
        lever: "reduce the tool landscape to one simple workflow",
        actions: [
          "List every system touched by the process.",
          "Mark manual transfers between tools.",
          "Decide which system leads the pilot.",
        ],
      },
      {
        label: "Capacity to pilot",
        description: "There is time and an owner to run a small pilot.",
        lever: "set up a small pilot with a clear owner",
        actions: [
          "Name one owner for decisions.",
          "Reserve a small weekly time window for tests.",
          "Scope the pilot so it can be measured within two to four weeks.",
        ],
      },
      {
        label: "Willingness to execute",
        description: "Decision makers are ready to test a pragmatic pilot.",
        lever: "secure the decision for a measurable quick win",
        actions: [
          "Define one success criterion before starting.",
          "Clarify which task should be relieved and which should not.",
          "Inform the team early about goal, limits, and human control.",
        ],
      },
    ],
    feedback: {
      low: "High leverage: this needs clarity before automation can carry weight.",
      mid: "Good pilot area: there is substance, but friction is still visible.",
      high: "Strong foundation: this area can accelerate the pilot.",
      prefix: "Your last answer shows",
    },
    bands: [
      {
        max: 44,
        label: "Create clarity first",
        phase: "Analyze + Structure",
        body: "The biggest lever is likely to make workflows, data, and responsibilities clearly visible first.",
        nextStep: "90-minute process intake and ASDAR baseline.",
      },
      {
        max: 71,
        label: "Prepare a pilot",
        phase: "Structure + Digitize",
        body: "There is enough substance for quick wins. Now it needs prioritization, data foundations, and a small test case.",
        nextStep: "Use-case selection, effort/value matrix, and pilot plan.",
      },
      {
        max: 100,
        label: "Start automation",
        phase: "Automate + Realize",
        body: "The foundation looks solid. A concrete workflow pilot with clear measurements is likely worth it.",
        nextStep: "Automation sprint with target metrics and portal status.",
      },
    ],
    resultTitle: "Personal result",
    lockedTitle: "Score unlocks after 5 answers",
    lockedBody:
      "Choose a profile and answer the readiness questions. Then you will see score, bottleneck, first lever, and time value.",
    bottleneck: "Biggest bottleneck",
    firstLever: "First automation lever",
    nextActions: "Next useful actions",
    nextStep: "Consulting step",
    people: "People involved",
    hours: "Manual hours per person/week",
    rate: "Internal hourly rate",
    automation: "Realistically reducible share",
    monthlyHours: "Hours freed per month",
    monthlyValue: "Value per month",
    annualValue: "Value per year",
    assumptionsTitle: "How the time value is calculated",
    assumptionsBody:
      "Formula: people x manual hours per week x 4.33 x reducible share. The euro value uses your internal hourly rate. This is orientation, not a guarantee.",
    cta: "Discuss result in a call",
    mobileCta: "Discuss result",
    next: "Next",
    back: "Back",
    editAnswers: "Edit answers",
    revealHint: "{count} answer(s) left until the result.",
    disclaimer:
      "Example calculation, not a guarantee. The real assessment happens with real process data in the project.",
  },
} as const;
